### ISSUE TITLE
Explore web page scraper 

### ISSUE THREAD

**Issue by harpermann** [eastham/adsb_actions#15]
- Wanted to check Dyacon Wx web page for how long since last update
- Selenium scraping may work.

**Comment by eastham** [comment]
Scraping with Selenium sure did work!  Implementation is here https://github.com/eastham/88nv_weather
I forget, was there anything else envisioned in this ticket?

**Comment by harpermann** [comment]
Nope, the ticket was for a check for last updated on the Dyacon web page alert on it.  Nice that it works!

**Comment by harpermann** [comment]
Selenium from python is easier than I thought.
