### ISSUE TITLE
Tower radio communications recording

### ISSUE THREAD

**Issue by harpermann** [eastham/adsb_actions#16]
- Set up scanner with Tower frequency
- Connect with headphone cable to usb
- Record on Mac or Raspi with microphone recorder

**Comment by harpermann** [comment]
Recieved used Uniden Bearcat BC125AT portable scanner.  

Working on 

- how it works?
- What kind of range does it have? (need a bigger or outdoor antenna?)
- how long a charge lasts?
- can run from USB?
- Connect to Mac for recording?

**Comment by eastham** [comment]
The Mac's we tend to have in the tower are not especially new, but they
still may not have an audio input, according to a quick search online:
https://discussions.apple.com/thread/254189941?sortBy=best

**Comment by harpermann** [comment]
We may be able to a use usb audio in cable. SABRENT USB Type A to 3.5mm Dual Function Audio Jack Active Adapter 20" Cable (CB-UA35)a.coHarper Mann510-599-2075 cellOn Apr 23, 2024, at 7:27 AM, eastham ***@***.***> wrote:﻿
The Mac's we tend to have in the tower are not especially new, but they

still may not have an audio input, according to a quick search online:

https://discussions.apple.com/thread/254189941?sortBy=best







On Mon, Apr 22, 2024 at 11:48 AM Harper Mann ***@***.***>

wrote:

**Comment by harpermann** [comment]
Spoke too soon.  Input -> USB is more interesting.  I remember doing it
with a dongle in the past but don't remember which one.  I'm doing a little
research.

H

Harper Mann
510-599-2075 mobile

**Comment by harpermann** [comment]
Normal Mic input won't work without an adapter as scanner headphone out is closer to **line in** higher input levels.  Mics are very low level so the scanner would distort without an attenuator. We need a sound card with **Line In**  

I ordered this one which advertises Mac compatibility:
https://www.amazon.com/dp/B0CKPL5HXZ?psc=1&smid=A2EDEOL32PF03V&ref_=chk_typ_imgToDp

As a test, I connected the Bearcat scanner to a Denon music speaker with line in and it works loud and clear.

**Comment by harpermann** [comment]
The scanner works a treat.  I can hear SFO approach / departure and OAK NORCAL App / Dep.  Oak tower was programmed in the scan but I can't hear it.

Here is the manual:
https://www.uniden.info/download/ompdf/BC125ATom.pdf

It will be set up so it monitors tower frequency when it's turned on.   We could get fancy and have tower interrupt ground or another frequency or two but let's start with just tower.  I ordered a potentially better antenna with Airband to try but the included antenna.

**Comment by harpermann** [comment]
https://github.com/eastham/adsb_actions/issues/21
Completed with this duplicate Issue.  Closing

**Comment by harpermann** [comment]
Google Drive setup for Raspi: https://medium.com/@artur.klauser/mounting-google-drive-on-raspberry-pi-dd15193d8138

**Comment by harpermann** [comment]
How to manager input and output volume on Debian

pactl list short - Gives names of sinks / sources

pactl info - gives current configuration

https://unix.stackexchange.com/questions/21089/how-to-use-command-line-to-change-volume

alsmixer - can switch between default output devices

harper@rpi5:~ $ pactl get-source-volume alsa_input.usb-Generic_CUBILUX_CA7-00.5.analog-stereo
Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
        balance 0.00

harper@rpi5:~ $ pactl set-source-volume alsa_input.usb-Generic_CUBILUX_CA7-00.5.analog-stereo 50
To set input volume to 50%

How to set up gdrive and rclone on Debian
https://medium.com/@artur.klauser/mounting-google-drive-on-raspberry-pi-dd15193d8138
