### ISSUE TITLE
Airport Live Webcam

### ISSUE THREAD

**Issue by harpermann** [eastham/adsb_actions#18]
FAA would like airport webcam(s).  

- What do they envision?
- More than one?
- Runway, operations, tie down line, weather?
- How to add webcam to web pages we want?  Maybe link on Dyacon page?  That would be cool
- How much resolution?  (Harper has Ring cams which are 1080p.  Need at least that I think)
- Good advertising if pilots (and FAA) can see conditions.
- Brings up: Hmm, what other stuff could we do that would be good record keeping and keep FAA super happy.
- Requirements?

**Comment by eastham** [comment]
Got it working!  See repo https://github.com/eastham/88nv_weather
