### ISSUE TITLE
Get Harper's Meshtastic working

### ISSUE THREAD

**Issue by harpermann** [eastham/adsb_actions#20]
I

**Comment by eastham** [comment]
Did you buy one unit or two?  May be hard to demo it if you don't have anyone else nearby to generate traffic to your device.  The local device does generate some "loopback" traffic on the serial port when it transmits, but I'm not sure position packets are included -- you can try it by enabling "fixed position" in the UI if you don't have a unit with GPS: https://meshtastic.org/docs/configuration/radio/position/

Code that pushes locations to readsb is here:  https://github.com/eastham/mesh_adsb/tree/main .  It also logs all traffic seen to stdout so may be a useful debugging tool for Meshtastic.

**Comment by harpermann** [comment]
Oh duhh. I bought one. I’ll get another one, they’re not expensive.  Good idea. Harper Mann510-599-2075 cellOn Apr 27, 2024, at 6:36 AM, eastham ***@***.***> wrote:﻿
Did you buy one unit or two?  May be hard to demo it if you don't have anyone else nearby to generate traffic to your device.  The local device does generate some "loopback" traffic on the serial port when it transmits, but I'm not sure position packets are included -- you can try it by enabling "fixed position" in the UI if you don't have a unit with GPS: https://meshtastic.org/docs/configuration/radio/position/
Code that pushes locations to readsb is here:  https://github.com/eastham/mesh_adsb/tree/main .  It also logs all traffic seen to stdout so may be a useful debugging tool for Meshtastic.

**Comment by eastham** [comment]
Well, if you fire up the one unit you have, you might get lucky and see
another nearby station.  If so, you should be able to see what it does.
But, in the middle of Silicon Valley, I do not have any stations I can hit
from my house, though there are a number of them closer to RHV.

**Comment by harpermann** [comment]
Got two units, flashed them with current stable, and set them up with 1000mwh batteries.  Both talk to my iPhone over bluetooth and send and receive messages.  I set them both to tracker mode and they both report location via mesh_adsb.  I plan to carry one on the playa and maybe keep the other one with Hesteah or at Camp.  Experiment as much as anything.  Meshtastics are pretty cool.

For this year, 2024, we have Promeheus reporting to the standard Pagers.  As some future time I want to experiment with sending Prom alerts to a Meshtastic channel and comparing Pager vs Meshtastic.
