### ISSUE TITLE
QuckTime recording tower radio

### ISSUE THREAD

**Issue by harpermann** [eastham/adsb_actions#21]
See if QuickTime can be set up in plist or something so it starts up on Mac boot to record radio Tx.  Add it to the list of monitored processes in Prometheus.

**Comment by harpermann** [comment]
![IMG_0298](https://github.com/eastham/adsb_actions/assets/2547812/c94a2aca-6f2c-4137-aab4-a0c10fd63036)

Scanner
https://www.amazon.com/Uniden-BC125AT-Alpha-Tagged-channels-Lightweight/dp/B00772MR0K
Soundcard
https://www.amazon.com/dp/B0CKPL5HXZ?psc=1&ref=ppx_yo2ov_dt_b_product_details

Macbook or similar that can receive USB Audio Line In.
Connect Male-to-male audio cable from Scanner headphones to sound card Line In.
Connnect USB Cable from Soundcard to Macbook

Using Audio Midi Setup.app on Macbook, set audio in to use the Line In for input.
<img width="647" alt="image" src="https://github.com/eastham/adsb_actions/assets/2547812/b38fa9d2-cce4-472a-aafd-c5bddf7d4f92">

Run QuickTime Player
  Select File -> New Audio Recording
  Hit the record button.

If you want to monitor the sound,  turn up the volume on the QuickTime recording app.

**Comment by harpermann** [comment]
We need to store the audio files somewhere.

See if it can be set up to record on boot.  Something like systemd on the Mac.  How to launch QuickTime in record mode.

**Comment by harpermann** [comment]
This works to fire off QuickTime recording from the CLI:
 osascript -e 'tell application "QuickTime Player" to activate' -e 'tell application "QuickTime Player" to start (new audio recording)'

**Comment by eastham** [comment]
Maybe keep it simple and write it to an sd card attached via usb to mac?

I did also go through the somewhat painful exercise of learning how to push
files to Google Drive and Dropbox recently.  Dropbox was most flexible for
images so I used that; code is in 88nv_weather/dropbox_upload.py -- 2GB
limit though.  Google Drive probably has unlimited storage, code not
checked in.

**Comment by eastham** [comment]
Thinking about it a bit more, it might come in handy to listen to this
audio during the event, which would argue for a cloud upload.
We often replay ads-b traces but wonder what was said.
Let me know if you're interested in the Drive code.

**Comment by harpermann** [comment]
You can create a working script with automator.app on the Mac
https://support.apple.com/guide/automator/use-a-shell-script-action-in-a-workflow-autbbd4cc11c/mac
<img width="990" alt="image" src="https://github.com/eastham/adsb_actions/assets/2547812/79ad8f93-22a0-4814-b703-bf3097f49f71">

Once created, save it Applications and add it to Login Items in System Preferences -> Users & Groups -> Login Items
Crontab is supposed to work as well so trying that. <-- DID NOT WORK

**Comment by harpermann** [comment]
QT plays the input on the Mac as it records.  Might be good to hook up a
speaker for better sound but it's not bad through my old 2015 Macbook.

For google drive, I'm thinking about some way for QT to write usable files
from a script rather than operator actions.  GDrive is simple to mount,
that's not a problem, but QT records it an Apple-ish format then saves in
something when you stop recording.  Not sure we can grab a file while it's
being written nor where that file might be.  Good old Apple obfuscation.

Harper Mann
510-599-2075 mobile

**Comment by harpermann** [comment]
Found where QT keeps it's unsaved recording:
/Users/harpermann/Library/Containers/com.apple.QuickTimePlayerX/Data/Library/Autosave Information/Unsaved QuickTime Player Document.qtpxcomposition/Audio Recording.m4a
Something like 2.5mb / minute.
You can copy the file out of there if you stop recording but not if recording as the file is incomplete. 

For now, I'm moving on to other projects.  We can have an Operator save the file on a regular basis.  Must stop recording and save to Google Drive mount.  Could be once / hr for whoever is on duty.

To automate further, we'd maybe need something besides QuickTime that's more CLI centric.
- start recording
- record for a time period
- stop recording
- copy the file to Google Drive with good naming
- restart recording.

NOTE: Consider running with an outside antenna with a BNC connector?
NOTE: Running Scanner off a USB battery bank is quiet, otherwise you get line hum.  Do we need to buy battery or is it available?  The built-in battery won't run all day and takes 14hrs to completely charge.

**Comment by eastham** [comment]
Unfortunately the operators in the tower are pretty easily distracted and
their computer skills are pretty light.  I don't think we can rely on them
to rotate the file reliably, maybe only once a day it would get done by
whoever closes up.  Maybe that's ok, but I wonder how difficult it will be
to accurately get to a particular timestamp on an 8hr+ file.

I wonder if anyone has already automated this somewhere on github...
certainly liveatc.net has it automated, but I don't know if their stuff if
public.

**Comment by harpermann** [comment]
Yeah, agree, and on further thought, I can script this.  Might not be pretty...  

- run a script to start the QT record
- kill it on interval
- copy the unsaved .m4a file to Google Drive
- start QT back up.

I'll also look for something already written.

**Comment by eastham** [comment]
I wonder if QT is the right thing to capture with.  Several people were
vouching for ffmpeg when I was looking into the webcam stuff, I believe it
does audio too.

**Comment by harpermann** [comment]
Yep, ffmpeg is better.  I'll set that up.  Thanks

https://apple.stackexchange.com/questions/326388/terminal-command-to-record-audio-through-macbook-microphone

Harper Mann
510-599-2075 mobile

**Comment by harpermann** [comment]
Got it working on Raspi as well as Mac.  Took a little figuring to get ffmpeg on the right device / etc with the sound card.  The script works well.  I want to add icecast to the ffmpeg output so we get files plus can listen real time on Icecast.   I need to create a plist and put the script in launchd on Mac and probably in init.d on Raspi.  Both will restart the process if it dies.  The script will just run rotating logs every X seconds which is set 3600 (1 hr) for now.  We can adjust.  I'll share the GDocs files and Icecast in a bit.  I think this is a decent solution but what do you think?  Do we need a speaker or something for wherever this lives?

**Comment by eastham** [comment]
That sounds awesome!  Yeah, the live stream would be handy for a couple of
things: 1. for staff who are monitoring operations from their trailers, a
lot of the time the aircraft transmissions can't quite get through the RV
walls.  2. if we want to set up a participant listening station somewhere.
I used to bring one with an old handheld in an ammo box, it got used quite
a bit.  Could have some headphones connected to the raspi on the TV in the
scenic tent...

**Comment by harpermann** [comment]
- Icecast is easy to set up on Raspi from apt
- There is a lag in the stream of up to 30 seconds.
- If we want more real time Radio sound, we could run speakers from the host with QuickTime or other player
- A2D (or any probably) input can be read by multiple processes
- Running two ffmpeg processes for production, one to write files and one to stream.  
- ffmpeg can probably stream to multiple targets but running 2 is easier to understand the config.
- still need plist and init.d setup

**Comment by harpermann** [comment]
Record command.  Script cd's into Google Drive
  /usr/local/bin/ffmpeg -f avfoundation -i ":2" -t $interval BRC_Airband_$timedate.mp3
Stream command
 /usr/local/bin/ffmpeg -f avfoundation -i ":2" -acodec libmp3lame -ab 32k -ac 1 -f mp3 icecast://source:playa2024@rpi5:8000/brc_airport_radio

Stream talks to Icecast2 running on another host but could be local.

**Comment by harpermann** [comment]
To get a process automagically started on user login, use launchd and launchctl
launchctl load ~/Library/LaunchAgents/com.harper.BrcRadioRecorder.plist
launchctl load ~/Library/LaunchAgents/com.harper.BrcRadioStreamer.plist

Use to stop / unload the scripts
launchctl unload ~/Library/LaunchAgents/com.harper.BrcRadioStreamer.plist

There are two scripts that call ffmpeg to do streaming and recording
/usr/local/bin/record_brc_airband.sh
/usr/local/bin/stream_brc_airband.sh

All files are in 
git@github.com:harpermann/brc_airport_prometheus.git

The recording and streaming scripts have been running for more than 10 hours with no errors.  If the processes die or are killed, launchd restarts them.  They start on login for user harpermann on my laptop for now.  We'll install these somewhere. 
NOTE: both shell scripts run on Raspian as well so could be implemented with init.d if we decide to run Linux.

I'm marking this one closed for pre-production.
