### ISSUE TITLE
Set up Windows VM on Macbook

### ISSUE THREAD

**Issue by harpermann** [eastham/adsb_actions#4]
So we can run Dyacon Wx station software and any other Windows based app we might need.  Try first https://www.cnet.com/tech/computing/heres-how-to-run-windows-10-on-your-mac-and-best-of-all-its-free/ for free or Parallels or Fusion or Virtual box if that doesn't work. Need to survey which one as haven't used them in a while.  Vbox or Fusion worked before.

**Comment by harpermann** [comment]
Here is the Dyacon application manual
https://dyacon.com/wp-content/uploads/2020/04/57-6089-Rev-C-DOC-Manual-Weather-Connect-SW-0640.pdf
Dyacon application
https://dyacon.com/product/cm-utility/

I have set up BootCamp on my Macbook so I can boot between Windows and MacOS.  May need to purchase a Windows Key but so far haven't needed it.  Note, I can't run Mac and WIndows at the same time (or haven't figured out how) but at least we have something for testing.  I'll set up the Dyacon App and maybe we can try it on a work day with the Wx hardware.

App needs some DLLs
https://answers.microsoft.com/en-us/windows/forum/all/error-message-for-msvcp140dll-and-vcruntime140dll/8c2c0803-08ac-4275-838e-b692077b5c9e
NOTE: Install both x86 and x64 versions.  I think the App is 32 bit..  
It works now

**Comment by harpermann** [comment]
Closing this one.  If we need a VM so can run both OS at the same time, Fusion or Parallels work.

**Comment by eastham** [comment]
Cool!  I guess we can test out the weather station after all at work
weekend.
